### ISSUE TITLE
problem indenting rows containing multiple and not requested  '\t' tabs

### ISSUE THREAD

**Issue by bitliner** [ishowshao/jformatter#3]
My initial code is the following:

```js
function(){
\t\t\tconsole.log('ciao');
}
```

If I format it using default options it still remains the same (3 tabs).

The expected behavior would be to reduce the number of tabs at line 2 from 3 tabs to only one (at least so common formatters work).

**Comment by ishowshao** [comment]
thank you, i will check and fix

**Comment by ishowshao** [comment]
hi, this is not jformatter's bug.

your code have a syntax error

```
function(){
\t\t\tconsole.log('ciao');
}
```

function declaration mast have a function name, your code have to change to 

```
function funcName(){
\t\t\tconsole.log('ciao');
}
```

esprima fail on syntax error code, so code will not be formatted

**Comment by ishowshao** [comment]
anyway, thank you for the first issue for me
